### ISSUE TITLE
[Feat] GitHub API 객체 개발

### ISSUE THREAD

**Issue by Zerohertz** [Zerohertz/zerohertzLib#62]
## 내용

[이런](https://api.github.com/repos/Zerohertz/zerohertzLib/pulls/56) 데이터를 파싱하고 문서화를 진행할 수 있게 개발 예정

## 작업 내용

- [x] `requests` module을 통한 GitHub API 호출 방법 조사
- [x] Label 명 을 입력하면 Issue 혹은 PR의 번호를 return하는 메서드 개발
- [x] Issue 혹은 PR의 번호를 입력하면 `title`과 `body`에 해당하는 `.md` 파일을 작성하는 메서드 개발 (Label 추가)

## 참고 사항

```python
>>> import zerohertzLib as zz
>>> gh = zz.api.GitHub("ghp_...")
>>> gh.label("feat/algorithm")
["23", "66"]
>>> gh.docs(54, output_filename="v0.2.1")
```

> v0.2.1.md

```markdown
# [v0.2.1] Release

## 작업 내용

+ :tada: Feat
   + API
      + `Discord` 객체화
      + 이미지 전송 메서드 개발 (resolves: #50)
   + Logging
      + `Discord` 객체 적용
   + Vision
      + 이미지 시각화 함수 `bbox`, `masks`, `text` 개발 (resolves: #49)
      + Bbox에 대한 전환 함수 개발 (`xyxy2xywh`, `xywh2xyxy`)
+ :art: Style
   + `numpy`에 대한 더 상세한 변화 (resolves: #53)
   + Type hint 검수 (resolves: #54)
   + MLOps submodule 내 객체의 camel case 수정
+ :memo: Docs
   + 문서 내 난잡한 type hint 제거
+ :hammer: Chore
   + Test image의 resolution 감소
   + PIL 의존성 해결 (#57)
```

**Comment by Zerohertz** [comment]
현재 버전은 `closed_at`이 존재하지 않아 수정 필요

```python
+ python sphinx/release_note.py --token ****
Traceback (most recent call last):
  File "sphinx/release_note.py", line 15, in <module>
    gh.release_note(sphinx_source_path=os.path.join(sphinx, "source"))
  File "/usr/local/lib/python3.8/site-packages/zerohertzLib/api/github.py", line 209, in release_note
    body = self._merge_release_note_version(version, data)
  File "/usr/local/lib/python3.8/site-packages/zerohertzLib/api/github.py", line 140, in _merge_release_note_version
    date = closed_at.split("T")[0].replace("-", "/")
AttributeError: 'NoneType' object has no attribute 'split'
script returned exit code 1
```
